version: '3.6'

services:
  product-server:
    image: 'postgres:13.1-alpine'
    container_name: product-server
    ports:
      - "1234:1234"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=ProductManagement